version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - DEFAULT_REGION=ap-northeast-2
      - EDGE_PORT=4566
      - SERVICES=s3,lambda,logs
    network_mode: bridge
    ports:
      - 4566:4566
      - '${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
